config: ./exps/AEexp.yaml
data:
  behaviors:
    center: 1
    left: 0
    right: 2
  dataset_name: 2020-01-26/2.0_1D_LCR_TML_T15_50/
  root_dir: /home/rosario/WRK/
experiment_name: TestAutoencoder
fov_description: LCR
logging:
  checkpoint: 10
  interval: 5
model: AE
model_params:
  dec_fc_sizes:
  - 8
  - 16
  enc_fc_sizes:
  - 16
  - 8
  latent_size: 3
training:
  batch_size: 60
  learning_rate: 0.001
  loss: MSE
  num_epochs: 40
  seed: 1
  shuffle_data: false
