!!python/object:utils.Namespace
_data:
  config: ./exps/exp1.yaml
  data:
    dataset_name: 2020-01-20/3.0_1D_OPEN_TDN_85/
    root_dir: /home/rosario/WRK/
  experiment_name: auto
  fov_description: LCR
  logging:
    checkpoint: 10
    interval: 5
  model:
    dec_fc_sizes:
    - 64
    - 32
    enc_conv_tuples:
    - - 1
      - 16
      - 3
      - 2
      - 2
      - 1
    enc_fc_sizes:
    - 16
    - 8
    latent_size: 1
  training:
    batch_size: 60
    beta: 1
    learning_rate: 0.001
    num_epochs: 40
    seed: 1
experiment_name: 3.0_1D_OPEN_TDN_85_B1
logdir: /home/rosario/WRK/MuSHR_cvae_experiments/2020-01-20/3.0_1D_OPEN_TDN_85_B1/
