config: cfg/conv_cvae.yaml
data:
  dataset_name: 2020-01-19/0.5_1D_LCR_TML_40/
  root_dir: /home/rosario/WRK/
experiment_name: auto
fov_description: LCR
logging:
  checkpoint: 10
  interval: 5
model:
  dec_fc_sizes:
  - 64
  - 32
  enc_conv_tuples:
  - - 1
    - 32
    - 3
    - 3
    - 2
    - 1
  - - 32
    - 16
    - 3
    - 2
    - 2
    - 1
  enc_fc_sizes:
  - 16
  - 8
  latent_size: 1
model_template: ConvConditionalVAE
training:
  batch_size: 60
  beta: 1
  learning_rate: 0.001
  num_epochs: 40
  seed: 1
  shuffle_data: false
