!!python/object:utils.Namespace
_data:
  config: ./exps/exp3.yaml
  data:
    behaviors: all
  experiment_name: auto
  logging:
    checkpoint: 10
    interval: 5
  model:
    dec_fc_sizes:
    - 64
    - 32
    enc_conv_tuples:
    - - 1
      - 32
      - 3
      - 3
      - 2
      - 1
    - - 32
      - 16
      - 3
      - 2
      - 2
      - 1
    enc_fc_sizes:
    - 16
    - 8
    latent_size: 1
  training:
    batch_size: 60
    beta: 0.5
    learning_rate: 0.001
    num_epochs: 40
    seed: 1
experiment_name: 1D_all_0p5
logdir: /home/rosario/WRK/MuSHR_cvae_experiments/2020-01-15/1D_all_0p5/
