config: exps/exp2.yaml
data:
  dataset_name: 2020-01-21/2.0_1D_LCR_TML_100/
  root_dir: /home/rosario/WRK/
experiment_name: LongTrain
fov_description: LCR
logging:
  checkpoint: 10
  interval: 5
model:
  enc_conv_tuples:
  - - 1
    - 64
    - 3
    - 2
    - 2
    - 1
  - - 64
    - 32
    - 3
    - 2
    - 2
    - 1
  - - 32
    - 16
    - 3
    - 2
    - 2
    - 1
  enc_fc_sizes:
  - 16
  - 45
training:
  batch_size: 60
  learning_rate: 0.001
  num_epochs: 100
  seed: 1
