config: ./exps/exp1.yaml
data:
  behaviors: LCR
dataset:
  behaviors: LCR
  maps: TML
  task: 3task
experiment_name: auto
logging:
  checkpoint: 10
  interval: 5
model:
  dec_fc_sizes:
  - 64
  - 32
  enc_conv_tuples:
  - - 1
    - 32
    - 3
    - 3
    - 2
    - 1
  - - 32
    - 16
    - 3
    - 2
    - 2
    - 1
  enc_fc_sizes:
  - 16
  - 8
  latent_size: 1
training:
  batch_size: 60
  beta: 2
  learning_rate: 0.001
  num_epochs: 40
  seed: 1
