config: ./exps/exp3.yaml
data:
  behaviors:
    default: 0
  dataset_name: 2020-01-26/XD_OPEN_TML_40/
  root_dir: /home/rosario/WRK/
experiment_name: auto
fov_description: OPEN
logging:
  checkpoint: 10
  interval: 5
model: ConvConditionalVAE
model_params:
  dec_fc_sizes:
  - 64
  - 32
  enc_conv_tuples:
  - - 1
    - 32
    - 3
    - 3
    - 2
    - 1
  - - 32
    - 16
    - 3
    - 2
    - 2
    - 1
  enc_fc_sizes:
  - 16
  - 8
  latent_size: 3
training:
  batch_size: 60
  beta: 1
  learning_rate: 0.001
  num_epochs: 40
  seed: 1
  shuffle_data: false
