AE_chkpt_name: 2020-01-26/TestAutoencoder
config: exps/AEBCexp.yaml
data:
  behaviors:
    center: 1
    left: 0
    right: 2
  dataset_name: 2020-01-26/2.0_1D_LCR_TML_T15_50/
  root_dir: /home/rosario/WRK/
experiment_name: TestAEBC
fov_description: LCR
logging:
  checkpoint: 10
  interval: 5
model: BC
modelAE_params:
  dec_fc_sizes:
  - 8
  - 16
  enc_fc_sizes:
  - 16
  - 8
  latent_size: 3
modelBC_params:
  enc_conv_tuples:
  - - 1
    - 32
    - 3
    - 3
    - 2
    - 1
  - - 32
    - 16
    - 3
    - 2
    - 2
    - 1
  enc_fc_sizes:
  - 16
  - 8
  latent_size: 0
training:
  batch_size: 60
  beta: 1
  learning_rate: 0.001
  loss: MSE_loss
  num_epochs: 40
  seed: 1
  shuffle_data: false
