!!python/object:utils.Namespace
_data:
  config: cfg/BC.yaml
  data:
    dataset_name: 2020-01-21/2.0_1D_LCR_TML_100/
    root_dir: /home/rosario/WRK/
  experiment_name: auto
  fov_description: LCR
  logging:
    checkpoint: 10
    interval: 5
  model:
    enc_conv_tuples:
    - - 1
      - 64
      - 3
      - 2
      - 2
      - 1
    - - 64
      - 32
      - 3
      - 2
      - 2
      - 1
    - - 32
      - 16
      - 3
      - 2
      - 2
      - 1
    enc_fc_sizes:
    - 16
    - 45
  training:
    batch_size: 60
    learning_rate: 0.001
    num_epochs: 40
    seed: 1
experiment_name: 2.0_1D_LCR_TML_100
logdir: /home/rosario/WRK/MuSHR_cvae_experiments/2020-01-22/2.0_1D_LCR_TML_100/
