config: ./exps/PCABCexp.yaml
data:
  behaviors:
    center: 1
    left: 0
    right: 2
  dataset_name: 2020-01-26/1.5_1D_LCR_TML_T15_40/
  root_dir: /home/rosario/WRK/
experiment_name: TestPCABC
fov_description: LCR
logging:
  checkpoint: 10
  interval: 5
model: BC
model_params:
  enc_conv_tuples:
  - - 1
    - 32
    - 3
    - 3
    - 2
    - 1
  - - 32
    - 16
    - 3
    - 2
    - 2
    - 1
  enc_fc_sizes:
  - 8
  - 16
  - 32
  latent_size: 3
training:
  batch_size: 60
  beta: 1
  learning_rate: 0.001
  loss: MSE_loss
  num_epochs: 40
  seed: 1
  shuffle_data: false
